title: Philip Ekholm
subtitle: Software Engineer
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Philip Ekholm
email: philipekholm@protonmail.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://philipekholm.github.io" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
facebook_url: "https://www.facebook.com/philip.ekholm"
linkedin_url: "https://www.linkedin.com/in/philip-ekholm-6543a114b/"
github_url: "https://github.com/PhilipEkholm"

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
