title: Philip Ekholm
description: IT-consultant based in Malmö, Sweden
author: Philip Ekholm
email: philipekholm@protonmail.com

url: "https://philipekholm.se"
baseurl: ""

# Social
github_url: "https://github.com/PhilipEkholm"
linkedin_url: "https://www.linkedin.com/in/philip-ekholm-6543a114b/"

# Build
markdown: kramdown
permalink: /professional/blog/:title/
sass:
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-prologue.gemspec
  - LICENSE.md
  - README.md
